name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for building the React app)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

        # Step 2: Set up Docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Step 3: Build Docker image
      - name: build a docker image
        run: |
          npm install
          docker build -t docker1img:vi2 .

      - name: list of docker images
        run: docker images

      # Step 4: Get Docker image ID
      - name: Get Docker image ID
        id: image_id
        run: |
          IMAGE_ID=$(docker images -q docker1img:vi2)
          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV

      - name: Create Docker container
        run: |
          docker run -d --name simpleRectjs ${{ env.IMAGE_ID }}
          docker ps -a

        # step 5: push the docker image to docker
      - name: stop docker container
        run: docker stop simpleRectjs
