name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for building the React app)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build a docker image
        run: |
          npm install
          docker build -t docker1img:vi2 .

      - name: list of docker images
        run: docker images

      - name: Pull Docker image
        run: docker pull charansaig1/simple-reactjs-app:d6c75bad50ea

      - name: create new Docker containerby usig the image
        run: docker run -d -p 3000:3000 --name sampleReactContainer d6c75bad50ea

      - name: check Docker container
        run: |
          echo "list of Docker containers"
          docker ps -a

          echo "list of Docker containers"
          docker stop sampleReactContainer

          docker ps -a
